### ISSUE TITLE
Debugging bpmn-js with min-dom

### ISSUE THREAD

**Issue by jrmora** [bpmn-io/min-dom#1]
Hi,

I'm trying to debug a viewer bpmn-js using either WebStorm or Node.js tools for Visual Studio and I have the same error when the debugger is passing by min-dom
Min-dom requires "domify" and inside, in the index.js there is a 

var div = document.createElement('div');

The error is that "document" is not recognized (obvious) because my test starts from a .js and not from a .html   

It is possible debug the bpmn-js from a html?  I want to see the changes happening directly in my own webpage.

Thank you

**Comment by gimbel** [comment]
I think this questions is best asked in our forum: https://forum.bpmn.io/

**Comment by jrmora** [comment]
OK, I'm agree
