### ISSUE TITLE
Expose valid typescript types

### ISSUE THREAD

**Issue by Yatoo2018** [bpmn-io/min-dom#14]
__Describe the bug__

Typescript definitions fail with `min-dom@3.2.0`.

The affected lines is: 

![image](https://user-images.githubusercontent.com/40135699/168951231-c1f0848e-e757-4474-b8e8-2f2a65339c6b.png)

__Steps to reproduce__

* Consume `min-dom@3.2.0` in TS project
* See `tsc` fail with above error

__Expected Behavior__

Typescript can consume the `min-dom` type definitions.

**Comment by nikku** [comment]
@marstamm Can you have a look? Seems to be a regression with the latest release?

**Comment by nikku** [comment]
We could also consider to add a [typescript integration test](https://github.com/nikku/didi/blob/master/test/integration/ts.spec.ts) to prevent this from happening again.

**Comment by marstamm** [comment]
@Yatoo2018 , we released a fix with 3.2.1. You should be able to consume the types now
