### ISSUE TITLE
Release a new version for the component-event change

### ISSUE THREAD

**Issue by jfastnacht** [bpmn-io/min-dom#20]
__What should we do?__

Please release a new version according to your versioning scheme.

__Why should we do it?__

The [component-event change](https://github.com/bpmn-io/min-dom/pull/19) is not considered in the dependencies of [bpmn-js](https://github.com/bpmn-io/bpmn-js) yet, because there is no new version of `min-dom`. This means that there is still a dependency in the dependency tree that does not contain proper license information right now.
While this is not as important software-wise, some organizations and tools insist on proper licensing information in all components of a software project. (And I'm stuck, because that's why I can't use `bpmn-js` right now in my project. 🙂 )

**Comment by nikku** [comment]
Released as v4.1.0.
