### ISSUE TITLE
Add CommonJS package export

### ISSUE THREAD

**Issue by danielkelemen** [bpmn-io/min-dom#22]
### Is your feature request related to a problem? Please describe.

In C7 we use the `form-js` which uses this package too. After updating to 1.8.0-1.8.6 versions, we get an error due to missing export for cjs `require` in the package.json:
```
ERROR in ./node_modules/@bpmn-io/form-js-editor/dist/index.cjs 12:13-31
Module not found: Error: Package path . is not exported from package /camunda-bpm-platform/webapps/frontend/node_modules/@bpmn-io/form-js-editor/node_modules/min-dom (see exports field in /camunda-bpm-platform/webapps/frontend/node_modules/@bpmn-io/form-js-editor/node_modules/min-dom/package.json)
 @ ./node_modules/@bpmn-io/form-js/dist/index.cjs 4:19-53
 @ ./ui/tasklist/client/scripts/form/directives/cam-tasklist-form-camunda.js 67:11-43
```

These versions use `min-dom` 5.0.0 which contains the new [package exports for esm `import` only](https://github.com/bpmn-io/min-dom/blob/main/package.json#L6).

Both `form-js` and `form-editor-js` have CommonJS support. The editor-js `form-js-editor/dist/index.cjs` requires the `min-dom` and I think this won't work without a `require` definition in the package exports:
```
var minDom = require('min-dom');
```

### Describe the solution you'd like

Add CommonJS support and package export.

### Describe alternatives you've considered

I am looking at solutions with webpack to resolve this but I think adding CommonJS support would be nicer and more helpful for other people too.

**Comment by nikku** [comment]
CC @Skaiir 

Looks like your upgrade to [`min-dom@5`](https://github.com/bpmn-io/min-dom/blob/main/CHANGELOG.md#410) broke contracts in form-js (CommonJS support). If you want to keep CommonJS support, consider reverting back to `min-dom@4`.
