### ISSUE TITLE
Not fully corrected closest-inline breaks use of bpmn-js inside shadow DOM

### ISSUE THREAD

**Issue by Firestorm87** [bpmn-io/min-dom#8]
Inside shadow-dom the toplevel element is an document-fragment instead of the document.

See also:
https://github.com/bpmn-io/min-dom/issues/5 (closest() breaks use of bpmn-js inside shadow DOM)

To fix that you have inlined "closet" an fixed:
`while (parent && parent !== document) {`
to
`while (currentElem && currentElem.nodeType !== document.DOCUMENT_NODE && currentElem.nodeType !== document.DOCUMENT_FRAGMENT_NODE) {`

But in the version on npmjs.com this correction is used only in "dist/index.js:276".
In the bundle is an second old implementation still alive.

"dist/index.jx:331":
`var closest$1 = function (element, selector, checkYoSelf) {
  var parent = checkYoSelf ? element : element.parentNode;

  while (parent && parent !== document) {
    if (matchesSelector$1(parent, selector)) return parent;
    parent = parent.parentNode;
  }
};`

npm-version 3.1.2:
[min-dom.zip](https://github.com/bpmn-io/min-dom/files/4556499/min-dom.zip)

**Comment by nikku** [comment]
Please use our existing but report template and include the concrete steps to reproduce your issue, preferibly a CodeSandbox _or_ HTML snippet.

**Comment by nikku** [comment]
Or, even better, maybe you could contribute a fix that improves the situation?

**Comment by nikku** [comment]
> But in the version on npmjs.com this correction is used only in "dist/index.js:276".
In the bundle is an second old implementation still alive.

@oguzeroglu Could you have a look if that is the case?

**Comment by nikku** [comment]
If so, we should release a proper version with rebuilt, fixed distributions.

**Comment by Firestorm87** [comment]
> Please use our existing but report template and include the concrete steps to reproduce your issue, preferibly a CodeSandbox _or_ HTML snippet.

npm install min-dom:3.1.2
open node_modules\min-dom\dist\index.js
look at line 276ff and 331ff

**Comment by oguzeroglu** [comment]
We've released v3.1.3 containing this fix: https://www.npmjs.com/package/min-dom

Thanks for letting us know about this issue!
